import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Gem Photobooth",
  description: "Generated by Hackthon Gem Team 2024",
  icons: {
    icon: '/favicon-32x32.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
      <head>
        <link rel="icon" href="/ favicon-32x32.png" />
        <title>GEM Photobooth</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
